apiVersion: batch/v1
kind: Job
metadata:
  name: job-ex
spec:
#  completions: 3
#  parallelism: 2
  activeDeadlineSeconds: 5
  template:
    spec:
      containers:
      - image: centos:7
        name: centos-container
        command: ["bash"]
        args:
        - "-c"
        - "echo 'Hello World'; sleep 25; echo 'Bye'"
      restartPolicy: Never
#      restartPolicy: OnFailure
#  backoffLimit: 3

