apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  replicas: 3
  selector:
    app: webui
    version: "1.14"
  template:
    metadata:
      name: pod-nginx
      labels:
        app: webui
        version: "1.14"
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
        ports:
        - containerPort: 80
