apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hostport
  name: hostport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostport
  template:
    metadata:
      labels:
        app: hostport
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        securityContext:
          privileged: true
        ports:
          - name: http
            containerPort: 80
            hostPort: 80
      hostNetwork: true

